/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZustandIndexRouteImport } from './routes/zustand/index'
import { Route as SafetySpecialSubstanceRouteImport } from './routes/safety/special-substance'
import { Route as SafetyMsdsRouteImport } from './routes/safety/msds'
import { Route as SafetyHazardousQuantityRouteImport } from './routes/safety/hazardous-quantity'
import { Route as SafetyHazardousChemicalRouteImport } from './routes/safety/hazardous-chemical'
import { Route as ItemsRegisterRouteImport } from './routes/items/register'
import { Route as ItemsPhotoPendingRouteImport } from './routes/items/photo-pending'
import { Route as ItemsIncomingPendingRouteImport } from './routes/items/incoming-pending'
import { Route as InstitutionLocationRouteImport } from './routes/institution/location'
import { Route as InstitutionInfoRouteImport } from './routes/institution/info'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZustandIndexRoute = ZustandIndexRouteImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySpecialSubstanceRoute = SafetySpecialSubstanceRouteImport.update({
  id: '/safety/special-substance',
  path: '/safety/special-substance',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyMsdsRoute = SafetyMsdsRouteImport.update({
  id: '/safety/msds',
  path: '/safety/msds',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyHazardousQuantityRoute = SafetyHazardousQuantityRouteImport.update({
  id: '/safety/hazardous-quantity',
  path: '/safety/hazardous-quantity',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyHazardousChemicalRoute = SafetyHazardousChemicalRouteImport.update({
  id: '/safety/hazardous-chemical',
  path: '/safety/hazardous-chemical',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRegisterRoute = ItemsRegisterRouteImport.update({
  id: '/items/register',
  path: '/items/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsPhotoPendingRoute = ItemsPhotoPendingRouteImport.update({
  id: '/items/photo-pending',
  path: '/items/photo-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIncomingPendingRoute = ItemsIncomingPendingRouteImport.update({
  id: '/items/incoming-pending',
  path: '/items/incoming-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionLocationRoute = InstitutionLocationRouteImport.update({
  id: '/institution/location',
  path: '/institution/location',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionInfoRoute = InstitutionInfoRouteImport.update({
  id: '/institution/info',
  path: '/institution/info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/institution/info': typeof InstitutionInfoRoute
  '/institution/location': typeof InstitutionLocationRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/zustand/': typeof ZustandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/institution/info': typeof InstitutionInfoRoute
  '/institution/location': typeof InstitutionLocationRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/zustand': typeof ZustandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/institution/info': typeof InstitutionInfoRoute
  '/institution/location': typeof InstitutionLocationRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/zustand/': typeof ZustandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/institution/info'
    | '/institution/location'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/zustand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/institution/info'
    | '/institution/location'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/zustand'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/institution/info'
    | '/institution/location'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/zustand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRoute
  RegisterRoute: typeof RegisterRoute
  InstitutionInfoRoute: typeof InstitutionInfoRoute
  InstitutionLocationRoute: typeof InstitutionLocationRoute
  ItemsIncomingPendingRoute: typeof ItemsIncomingPendingRoute
  ItemsPhotoPendingRoute: typeof ItemsPhotoPendingRoute
  ItemsRegisterRoute: typeof ItemsRegisterRoute
  SafetyHazardousChemicalRoute: typeof SafetyHazardousChemicalRoute
  SafetyHazardousQuantityRoute: typeof SafetyHazardousQuantityRoute
  SafetyMsdsRoute: typeof SafetyMsdsRoute
  SafetySpecialSubstanceRoute: typeof SafetySpecialSubstanceRoute
  ZustandIndexRoute: typeof ZustandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand/'
      preLoaderRoute: typeof ZustandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/special-substance': {
      id: '/safety/special-substance'
      path: '/safety/special-substance'
      fullPath: '/safety/special-substance'
      preLoaderRoute: typeof SafetySpecialSubstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/msds': {
      id: '/safety/msds'
      path: '/safety/msds'
      fullPath: '/safety/msds'
      preLoaderRoute: typeof SafetyMsdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/hazardous-quantity': {
      id: '/safety/hazardous-quantity'
      path: '/safety/hazardous-quantity'
      fullPath: '/safety/hazardous-quantity'
      preLoaderRoute: typeof SafetyHazardousQuantityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/hazardous-chemical': {
      id: '/safety/hazardous-chemical'
      path: '/safety/hazardous-chemical'
      fullPath: '/safety/hazardous-chemical'
      preLoaderRoute: typeof SafetyHazardousChemicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/register': {
      id: '/items/register'
      path: '/items/register'
      fullPath: '/items/register'
      preLoaderRoute: typeof ItemsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/photo-pending': {
      id: '/items/photo-pending'
      path: '/items/photo-pending'
      fullPath: '/items/photo-pending'
      preLoaderRoute: typeof ItemsPhotoPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/incoming-pending': {
      id: '/items/incoming-pending'
      path: '/items/incoming-pending'
      fullPath: '/items/incoming-pending'
      preLoaderRoute: typeof ItemsIncomingPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/location': {
      id: '/institution/location'
      path: '/institution/location'
      fullPath: '/institution/location'
      preLoaderRoute: typeof InstitutionLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/info': {
      id: '/institution/info'
      path: '/institution/info'
      fullPath: '/institution/info'
      preLoaderRoute: typeof InstitutionInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRoute,
  RegisterRoute: RegisterRoute,
  InstitutionInfoRoute: InstitutionInfoRoute,
  InstitutionLocationRoute: InstitutionLocationRoute,
  ItemsIncomingPendingRoute: ItemsIncomingPendingRoute,
  ItemsPhotoPendingRoute: ItemsPhotoPendingRoute,
  ItemsRegisterRoute: ItemsRegisterRoute,
  SafetyHazardousChemicalRoute: SafetyHazardousChemicalRoute,
  SafetyHazardousQuantityRoute: SafetyHazardousQuantityRoute,
  SafetyMsdsRoute: SafetyMsdsRoute,
  SafetySpecialSubstanceRoute: SafetySpecialSubstanceRoute,
  ZustandIndexRoute: ZustandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
