/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterTermsRouteImport } from './routes/register-terms'
import { Route as RegisterResetPasswordCompleteRouteImport } from './routes/register-reset-password-complete'
import { Route as RegisterPasswordRouteImport } from './routes/register-password'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as RegisterIdentityVerificationRouteImport } from './routes/register-identity-verification'
import { Route as RegisterEmailVerificationRouteImport } from './routes/register-email-verification'
import { Route as RegisterAccountExistsRouteImport } from './routes/register-account-exists'
import { Route as RegisterAccountCheckRouteImport } from './routes/register-account-check'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginVerifyRouteImport } from './routes/login-verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindAccountResetPasswordRouteImport } from './routes/find-account-reset-password'
import { Route as FindAccountRouteImport } from './routes/find-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsStorageLocationRouteImport } from './routes/settings/storage-location'
import { Route as SettingsProcessRouteImport } from './routes/settings/process'
import { Route as SettingsMemberRouteImport } from './routes/settings/member'
import { Route as SettingsInventoryConfigRouteImport } from './routes/settings/inventory-config'
import { Route as SettingsGroupRouteImport } from './routes/settings/group'
import { Route as SettingsCategoryRouteImport } from './routes/settings/category'
import { Route as SafetySpecialSubstanceRouteImport } from './routes/safety/special-substance'
import { Route as SafetyMsdsRouteImport } from './routes/safety/msds'
import { Route as SafetyHazardousQuantityRouteImport } from './routes/safety/hazardous-quantity'
import { Route as SafetyHazardousChemicalRouteImport } from './routes/safety/hazardous-chemical'
import { Route as ReservationPreparingRouteImport } from './routes/reservation/preparing'
import { Route as ItemsRegisterRouteImport } from './routes/items/register'
import { Route as ItemsPhotoPendingRouteImport } from './routes/items/photo-pending'
import { Route as ItemsIncomingPendingRouteImport } from './routes/items/incoming-pending'
import { Route as InventoryPreparingRouteImport } from './routes/inventory/preparing'

const RegisterTermsRoute = RegisterTermsRouteImport.update({
  id: '/register-terms',
  path: '/register-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterResetPasswordCompleteRoute =
  RegisterResetPasswordCompleteRouteImport.update({
    id: '/register-reset-password-complete',
    path: '/register-reset-password-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterPasswordRoute = RegisterPasswordRouteImport.update({
  id: '/register-password',
  path: '/register-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIdentityVerificationRoute =
  RegisterIdentityVerificationRouteImport.update({
    id: '/register-identity-verification',
    path: '/register-identity-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterEmailVerificationRoute =
  RegisterEmailVerificationRouteImport.update({
    id: '/register-email-verification',
    path: '/register-email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterAccountExistsRoute = RegisterAccountExistsRouteImport.update({
  id: '/register-account-exists',
  path: '/register-account-exists',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAccountCheckRoute = RegisterAccountCheckRouteImport.update({
  id: '/register-account-check',
  path: '/register-account-check',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login-verify',
  path: '/login-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAccountResetPasswordRoute =
  FindAccountResetPasswordRouteImport.update({
    id: '/find-account-reset-password',
    path: '/find-account-reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const FindAccountRoute = FindAccountRouteImport.update({
  id: '/find-account',
  path: '/find-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageLocationRoute = SettingsStorageLocationRouteImport.update({
  id: '/settings/storage-location',
  path: '/settings/storage-location',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProcessRoute = SettingsProcessRouteImport.update({
  id: '/settings/process',
  path: '/settings/process',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMemberRoute = SettingsMemberRouteImport.update({
  id: '/settings/member',
  path: '/settings/member',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInventoryConfigRoute = SettingsInventoryConfigRouteImport.update({
  id: '/settings/inventory-config',
  path: '/settings/inventory-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGroupRoute = SettingsGroupRouteImport.update({
  id: '/settings/group',
  path: '/settings/group',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoryRoute = SettingsCategoryRouteImport.update({
  id: '/settings/category',
  path: '/settings/category',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySpecialSubstanceRoute = SafetySpecialSubstanceRouteImport.update({
  id: '/safety/special-substance',
  path: '/safety/special-substance',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyMsdsRoute = SafetyMsdsRouteImport.update({
  id: '/safety/msds',
  path: '/safety/msds',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyHazardousQuantityRoute = SafetyHazardousQuantityRouteImport.update({
  id: '/safety/hazardous-quantity',
  path: '/safety/hazardous-quantity',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyHazardousChemicalRoute = SafetyHazardousChemicalRouteImport.update({
  id: '/safety/hazardous-chemical',
  path: '/safety/hazardous-chemical',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationPreparingRoute = ReservationPreparingRouteImport.update({
  id: '/reservation/preparing',
  path: '/reservation/preparing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRegisterRoute = ItemsRegisterRouteImport.update({
  id: '/items/register',
  path: '/items/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsPhotoPendingRoute = ItemsPhotoPendingRouteImport.update({
  id: '/items/photo-pending',
  path: '/items/photo-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIncomingPendingRoute = ItemsIncomingPendingRouteImport.update({
  id: '/items/incoming-pending',
  path: '/items/incoming-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryPreparingRoute = InventoryPreparingRouteImport.update({
  id: '/inventory/preparing',
  path: '/inventory/preparing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/find-account-reset-password': typeof FindAccountResetPasswordRoute
  '/login': typeof LoginRoute
  '/login-verify': typeof LoginVerifyRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/register-account-check': typeof RegisterAccountCheckRoute
  '/register-account-exists': typeof RegisterAccountExistsRoute
  '/register-email-verification': typeof RegisterEmailVerificationRoute
  '/register-identity-verification': typeof RegisterIdentityVerificationRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/register-password': typeof RegisterPasswordRoute
  '/register-reset-password-complete': typeof RegisterResetPasswordCompleteRoute
  '/register-terms': typeof RegisterTermsRoute
  '/inventory/preparing': typeof InventoryPreparingRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/reservation/preparing': typeof ReservationPreparingRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/settings/category': typeof SettingsCategoryRoute
  '/settings/group': typeof SettingsGroupRoute
  '/settings/inventory-config': typeof SettingsInventoryConfigRoute
  '/settings/member': typeof SettingsMemberRoute
  '/settings/process': typeof SettingsProcessRoute
  '/settings/storage-location': typeof SettingsStorageLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/find-account-reset-password': typeof FindAccountResetPasswordRoute
  '/login': typeof LoginRoute
  '/login-verify': typeof LoginVerifyRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/register-account-check': typeof RegisterAccountCheckRoute
  '/register-account-exists': typeof RegisterAccountExistsRoute
  '/register-email-verification': typeof RegisterEmailVerificationRoute
  '/register-identity-verification': typeof RegisterIdentityVerificationRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/register-password': typeof RegisterPasswordRoute
  '/register-reset-password-complete': typeof RegisterResetPasswordCompleteRoute
  '/register-terms': typeof RegisterTermsRoute
  '/inventory/preparing': typeof InventoryPreparingRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/reservation/preparing': typeof ReservationPreparingRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/settings/category': typeof SettingsCategoryRoute
  '/settings/group': typeof SettingsGroupRoute
  '/settings/inventory-config': typeof SettingsInventoryConfigRoute
  '/settings/member': typeof SettingsMemberRoute
  '/settings/process': typeof SettingsProcessRoute
  '/settings/storage-location': typeof SettingsStorageLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/find-account-reset-password': typeof FindAccountResetPasswordRoute
  '/login': typeof LoginRoute
  '/login-verify': typeof LoginVerifyRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/register-account-check': typeof RegisterAccountCheckRoute
  '/register-account-exists': typeof RegisterAccountExistsRoute
  '/register-email-verification': typeof RegisterEmailVerificationRoute
  '/register-identity-verification': typeof RegisterIdentityVerificationRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/register-password': typeof RegisterPasswordRoute
  '/register-reset-password-complete': typeof RegisterResetPasswordCompleteRoute
  '/register-terms': typeof RegisterTermsRoute
  '/inventory/preparing': typeof InventoryPreparingRoute
  '/items/incoming-pending': typeof ItemsIncomingPendingRoute
  '/items/photo-pending': typeof ItemsPhotoPendingRoute
  '/items/register': typeof ItemsRegisterRoute
  '/reservation/preparing': typeof ReservationPreparingRoute
  '/safety/hazardous-chemical': typeof SafetyHazardousChemicalRoute
  '/safety/hazardous-quantity': typeof SafetyHazardousQuantityRoute
  '/safety/msds': typeof SafetyMsdsRoute
  '/safety/special-substance': typeof SafetySpecialSubstanceRoute
  '/settings/category': typeof SettingsCategoryRoute
  '/settings/group': typeof SettingsGroupRoute
  '/settings/inventory-config': typeof SettingsInventoryConfigRoute
  '/settings/member': typeof SettingsMemberRoute
  '/settings/process': typeof SettingsProcessRoute
  '/settings/storage-location': typeof SettingsStorageLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-account'
    | '/find-account-reset-password'
    | '/login'
    | '/login-verify'
    | '/main'
    | '/register'
    | '/register-account-check'
    | '/register-account-exists'
    | '/register-email-verification'
    | '/register-identity-verification'
    | '/register-organization'
    | '/register-password'
    | '/register-reset-password-complete'
    | '/register-terms'
    | '/inventory/preparing'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/reservation/preparing'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/settings/category'
    | '/settings/group'
    | '/settings/inventory-config'
    | '/settings/member'
    | '/settings/process'
    | '/settings/storage-location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-account'
    | '/find-account-reset-password'
    | '/login'
    | '/login-verify'
    | '/main'
    | '/register'
    | '/register-account-check'
    | '/register-account-exists'
    | '/register-email-verification'
    | '/register-identity-verification'
    | '/register-organization'
    | '/register-password'
    | '/register-reset-password-complete'
    | '/register-terms'
    | '/inventory/preparing'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/reservation/preparing'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/settings/category'
    | '/settings/group'
    | '/settings/inventory-config'
    | '/settings/member'
    | '/settings/process'
    | '/settings/storage-location'
  id:
    | '__root__'
    | '/'
    | '/find-account'
    | '/find-account-reset-password'
    | '/login'
    | '/login-verify'
    | '/main'
    | '/register'
    | '/register-account-check'
    | '/register-account-exists'
    | '/register-email-verification'
    | '/register-identity-verification'
    | '/register-organization'
    | '/register-password'
    | '/register-reset-password-complete'
    | '/register-terms'
    | '/inventory/preparing'
    | '/items/incoming-pending'
    | '/items/photo-pending'
    | '/items/register'
    | '/reservation/preparing'
    | '/safety/hazardous-chemical'
    | '/safety/hazardous-quantity'
    | '/safety/msds'
    | '/safety/special-substance'
    | '/settings/category'
    | '/settings/group'
    | '/settings/inventory-config'
    | '/settings/member'
    | '/settings/process'
    | '/settings/storage-location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindAccountRoute: typeof FindAccountRoute
  FindAccountResetPasswordRoute: typeof FindAccountResetPasswordRoute
  LoginRoute: typeof LoginRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  MainRoute: typeof MainRoute
  RegisterRoute: typeof RegisterRoute
  RegisterAccountCheckRoute: typeof RegisterAccountCheckRoute
  RegisterAccountExistsRoute: typeof RegisterAccountExistsRoute
  RegisterEmailVerificationRoute: typeof RegisterEmailVerificationRoute
  RegisterIdentityVerificationRoute: typeof RegisterIdentityVerificationRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  RegisterPasswordRoute: typeof RegisterPasswordRoute
  RegisterResetPasswordCompleteRoute: typeof RegisterResetPasswordCompleteRoute
  RegisterTermsRoute: typeof RegisterTermsRoute
  InventoryPreparingRoute: typeof InventoryPreparingRoute
  ItemsIncomingPendingRoute: typeof ItemsIncomingPendingRoute
  ItemsPhotoPendingRoute: typeof ItemsPhotoPendingRoute
  ItemsRegisterRoute: typeof ItemsRegisterRoute
  ReservationPreparingRoute: typeof ReservationPreparingRoute
  SafetyHazardousChemicalRoute: typeof SafetyHazardousChemicalRoute
  SafetyHazardousQuantityRoute: typeof SafetyHazardousQuantityRoute
  SafetyMsdsRoute: typeof SafetyMsdsRoute
  SafetySpecialSubstanceRoute: typeof SafetySpecialSubstanceRoute
  SettingsCategoryRoute: typeof SettingsCategoryRoute
  SettingsGroupRoute: typeof SettingsGroupRoute
  SettingsInventoryConfigRoute: typeof SettingsInventoryConfigRoute
  SettingsMemberRoute: typeof SettingsMemberRoute
  SettingsProcessRoute: typeof SettingsProcessRoute
  SettingsStorageLocationRoute: typeof SettingsStorageLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-terms': {
      id: '/register-terms'
      path: '/register-terms'
      fullPath: '/register-terms'
      preLoaderRoute: typeof RegisterTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-reset-password-complete': {
      id: '/register-reset-password-complete'
      path: '/register-reset-password-complete'
      fullPath: '/register-reset-password-complete'
      preLoaderRoute: typeof RegisterResetPasswordCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-password': {
      id: '/register-password'
      path: '/register-password'
      fullPath: '/register-password'
      preLoaderRoute: typeof RegisterPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-identity-verification': {
      id: '/register-identity-verification'
      path: '/register-identity-verification'
      fullPath: '/register-identity-verification'
      preLoaderRoute: typeof RegisterIdentityVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-email-verification': {
      id: '/register-email-verification'
      path: '/register-email-verification'
      fullPath: '/register-email-verification'
      preLoaderRoute: typeof RegisterEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-account-exists': {
      id: '/register-account-exists'
      path: '/register-account-exists'
      fullPath: '/register-account-exists'
      preLoaderRoute: typeof RegisterAccountExistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-account-check': {
      id: '/register-account-check'
      path: '/register-account-check'
      fullPath: '/register-account-check'
      preLoaderRoute: typeof RegisterAccountCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-verify': {
      id: '/login-verify'
      path: '/login-verify'
      fullPath: '/login-verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-account-reset-password': {
      id: '/find-account-reset-password'
      path: '/find-account-reset-password'
      fullPath: '/find-account-reset-password'
      preLoaderRoute: typeof FindAccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-account': {
      id: '/find-account'
      path: '/find-account'
      fullPath: '/find-account'
      preLoaderRoute: typeof FindAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage-location': {
      id: '/settings/storage-location'
      path: '/settings/storage-location'
      fullPath: '/settings/storage-location'
      preLoaderRoute: typeof SettingsStorageLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/process': {
      id: '/settings/process'
      path: '/settings/process'
      fullPath: '/settings/process'
      preLoaderRoute: typeof SettingsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/member': {
      id: '/settings/member'
      path: '/settings/member'
      fullPath: '/settings/member'
      preLoaderRoute: typeof SettingsMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inventory-config': {
      id: '/settings/inventory-config'
      path: '/settings/inventory-config'
      fullPath: '/settings/inventory-config'
      preLoaderRoute: typeof SettingsInventoryConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/group': {
      id: '/settings/group'
      path: '/settings/group'
      fullPath: '/settings/group'
      preLoaderRoute: typeof SettingsGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/category': {
      id: '/settings/category'
      path: '/settings/category'
      fullPath: '/settings/category'
      preLoaderRoute: typeof SettingsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/special-substance': {
      id: '/safety/special-substance'
      path: '/safety/special-substance'
      fullPath: '/safety/special-substance'
      preLoaderRoute: typeof SafetySpecialSubstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/msds': {
      id: '/safety/msds'
      path: '/safety/msds'
      fullPath: '/safety/msds'
      preLoaderRoute: typeof SafetyMsdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/hazardous-quantity': {
      id: '/safety/hazardous-quantity'
      path: '/safety/hazardous-quantity'
      fullPath: '/safety/hazardous-quantity'
      preLoaderRoute: typeof SafetyHazardousQuantityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/hazardous-chemical': {
      id: '/safety/hazardous-chemical'
      path: '/safety/hazardous-chemical'
      fullPath: '/safety/hazardous-chemical'
      preLoaderRoute: typeof SafetyHazardousChemicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/preparing': {
      id: '/reservation/preparing'
      path: '/reservation/preparing'
      fullPath: '/reservation/preparing'
      preLoaderRoute: typeof ReservationPreparingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/register': {
      id: '/items/register'
      path: '/items/register'
      fullPath: '/items/register'
      preLoaderRoute: typeof ItemsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/photo-pending': {
      id: '/items/photo-pending'
      path: '/items/photo-pending'
      fullPath: '/items/photo-pending'
      preLoaderRoute: typeof ItemsPhotoPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/incoming-pending': {
      id: '/items/incoming-pending'
      path: '/items/incoming-pending'
      fullPath: '/items/incoming-pending'
      preLoaderRoute: typeof ItemsIncomingPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/preparing': {
      id: '/inventory/preparing'
      path: '/inventory/preparing'
      fullPath: '/inventory/preparing'
      preLoaderRoute: typeof InventoryPreparingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindAccountRoute: FindAccountRoute,
  FindAccountResetPasswordRoute: FindAccountResetPasswordRoute,
  LoginRoute: LoginRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  MainRoute: MainRoute,
  RegisterRoute: RegisterRoute,
  RegisterAccountCheckRoute: RegisterAccountCheckRoute,
  RegisterAccountExistsRoute: RegisterAccountExistsRoute,
  RegisterEmailVerificationRoute: RegisterEmailVerificationRoute,
  RegisterIdentityVerificationRoute: RegisterIdentityVerificationRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  RegisterPasswordRoute: RegisterPasswordRoute,
  RegisterResetPasswordCompleteRoute: RegisterResetPasswordCompleteRoute,
  RegisterTermsRoute: RegisterTermsRoute,
  InventoryPreparingRoute: InventoryPreparingRoute,
  ItemsIncomingPendingRoute: ItemsIncomingPendingRoute,
  ItemsPhotoPendingRoute: ItemsPhotoPendingRoute,
  ItemsRegisterRoute: ItemsRegisterRoute,
  ReservationPreparingRoute: ReservationPreparingRoute,
  SafetyHazardousChemicalRoute: SafetyHazardousChemicalRoute,
  SafetyHazardousQuantityRoute: SafetyHazardousQuantityRoute,
  SafetyMsdsRoute: SafetyMsdsRoute,
  SafetySpecialSubstanceRoute: SafetySpecialSubstanceRoute,
  SettingsCategoryRoute: SettingsCategoryRoute,
  SettingsGroupRoute: SettingsGroupRoute,
  SettingsInventoryConfigRoute: SettingsInventoryConfigRoute,
  SettingsMemberRoute: SettingsMemberRoute,
  SettingsProcessRoute: SettingsProcessRoute,
  SettingsStorageLocationRoute: SettingsStorageLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
